<!DOCTYPE html>
<html>
  <head>
    <title><?= $message ?></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>body { font-family: Arial, sans; text-align: left; }</style>
  </head>
  <body>
    <header>
    <h1><?= $code ?>: <?= $message ?></h1>
    <?php if ($extended_info): ?>
      <?php if ($extended_data instanceof throwable): ?>
        <pre><b>Throwable:</b> <?= print_r($extended_data, true); ?></pre>
      <?php else: ?>
        <h4><?= $extended_data ?></h4>
      <?php endif ?>
    <?php endif ?>
    </header>
  </body>
</html>
